import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

import Providers from "@/components/query-provider";
import { cn } from "@/lib/utils";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
